---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: app03
  namespace: flux-system
spec:
  chart:
    spec:
      chart: ./charts/app03
      sourceRef:
        kind: GitRepository
        name: flux-system
  install:
    createNamespace: true
  interval: 1m0s
  targetNamespace: sample-apps
  values:
    service:
      name: app02
      port: 83
      type: LoadBalancer

