---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: app01
  namespace: flux-system
spec:
  chart:
    spec:
      chart: app01
      sourceRef:
        kind: HelmRepository
        name: apprepo
  interval: 1m0s
  install:
    createNamespace: true
  targetNamespace: sample-apps
  values:
    service:
      type: LoadBalancer
      port: 81
