---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: apprepo
  namespace: flux-system
spec:
  interval: 5m0s
  url:  https://devopsapp84.github.io/flux2-capabilities-clean
